### ISSUE TITLE
Map chrashes when going to high or too low.

### ISSUE THREAD

**Issue by AZProductions** [podusowski/walkers#1]
Hello, thanks for sharing this code! I've found one annoyance, when zooming out to the maximum and moving the map to the top of the world/bottom of the world, it panics and shuts down. Perhaps a limit or max height should be added, might try to solve that later.
```
thread 'main' panicked at 'attempt to subtract with overflow', src\mercator.rs:53:16
```

Thanks again.

**Comment by podusowski** [comment]
Fixed in 0.2.0. It still behaves weird on extreme zooms (when server returns 400), but it needs some deeper thought.
