### ISSUE TITLE
OpenStreetMap usage policy

### ISSUE THREAD

**Issue by podusowski** [podusowski/walkers#104]
There are couple of requirements that OSM put on the clients.

https://operations.osmfoundation.org/policies/tiles/

# Hard requirements
- [x] Clearly display [license](https://wiki.openstreetmap.org/wiki/License) [attribution](https://wiki.osmfoundation.org/wiki/Licence/Attribution_Guidelines).
- [x] Valid [HTTP User-Agent](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent) identifying application. Faking another app’s User-Agent WILL get you blocked. Using a library’s default User-Agent is NOT recommended. If a device automatically sends an X-Requested-With header with an application specific Application ID, this will be considered an acceptable substitute for the HTTP User-Agent, although we still recommend setting a valid HTTP User-Agent for the application.
- [x] When coming from a web page, a valid [HTTP Referer](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referer). Apps generally do not have a HTTP referer.
- [x] https://github.com/podusowski/walkers/pull/103 Cache Tile downloads locally according to HTTP Expiry Header, alternatively a minimum of 7 days.
- [x] Maximum of 2 download connections. (Unmodified web browsers’ download limits are acceptable.) (related: https://github.com/podusowski/walkers/issues/116)

# Recommendations
- [ ] Recommended: Do not hardcode any URL to tile.openstreetmap.org as doing so will limit your ability to react if the service is disrupted or blocked. In particular, switching should be possible without requiring a software update.
- [ ] Recommended: add a link to https://www.openstreetmap.org/fixthemap to allow your users to report and fix problems in our data.

**Comment by noktoborus** [comment]
>  Maximum of 2 download connections. (Unmodified web browsers’ download limits are acceptable.)

In the https://t.me/OpenStreetMapOrg/  it was explained to me that this limitation is related to scripts downloading the world, not for user-end programs. But as far as I remember, OsmAnd were asked to switch to their own file server, but it is still not affected to library because:
1. The total number of downloaded tiles is small
2. Programs using the library should deal with this themselves, but need move the 'http-agent' option closer to up-level API.

**Comment by podusowski** [comment]
> When coming from a web page, a valid [HTTP Referer](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referer).

This seems to be working out of the box.

![image](https://github.com/podusowski/walkers/assets/2226778/0088b7b8-0d9e-40f1-a4d8-0b6018dc87c1)
