### ISSUE TITLE
Remove global zoom limitation and split tile's zoom and viewport zoom

### ISSUE THREAD

**Issue by noktoborus** [podusowski/walkers#110]
E.g. walkers can draw scaled z19 tiles on z21 even if source (like osm.org) not supported it.

This is convenient if different sources support different zoom and the way to support smooth zooming in future.

I made a stub partially covering my request but it is terrible solution: https://github.com/podusowski/walkers/pull/101

**Comment by podusowski** [comment]
The idea seems sound, though I think I would start with a min/max pair (say `struct ZoomLevels`) which is returned from `Tiles`. Also, your PR is mixed with this `click` branch, which I don't really know what to do with it. It kind of breaks the idea of `my_position`, which would typically be a position obtained from the GPS or something and provided by the app. And if app wanted to jump somewhere, you'd call `MapMemory::center_at` (might want to rename to `jump_to` when I think about it now :)).

**Comment by noktoborus** [comment]
> really know what to do with it.

i will drop this

**Comment by podusowski** [comment]
Getting position under the mouse is a nice example though.

**Comment by noktoborus** [comment]
> Also, your PR is mixed with this click branch,

I will drop zoom branch.

> which I don't really know what to do with it. It kind of breaks the idea of my_position

Now no one provide GPS data, so I assume what click to set position is good idea.

I have reworked the `click` branch, could you take a look? :)

**Comment by podusowski** [comment]
> Now no one provide GPS data

I'm thinking about adding it to the demo soon.

**Comment by podusowski** [comment]
This is all I see there.

![image](https://github.com/podusowski/walkers/assets/2226778/312c7461-9d94-46d4-9018-50280fc08c40)

**Comment by noktoborus** [comment]
> This is all I see there.

sorry, I forgot to commit the new changes :)
