### ISSUE TITLE
Download tiles in parallel

### ISSUE THREAD

**Issue by noktoborus** [podusowski/walkers#116]
Now one tile at a time:
![image](https://github.com/podusowski/walkers/assets/324098/bb1ec020-7b5c-4010-a966-fc38ad7af3ea)

Map can be displayed faster if download tiles in parallel

**Comment by noktoborus** [comment]
additionally, here is a lot of trash queries:

![image](https://github.com/podusowski/walkers/assets/324098/6f5c0913-7571-455d-9c2e-0c9789c7a671)

from five to 6 requests per tile (some of them are from cache).

Looks a little buggy.

**Comment by podusowski** [comment]
https://github.com/podusowski/walkers/pull/121
