### ISSUE TITLE
Access zoom level from MapMemory

### ISSUE THREAD

**Issue by tfoldi** [podusowski/walkers#163]
I need to persist a view with its settings (center position and zoom level), but as I see there is no method to retrieve the current Zoom level. Can you please add it? Or I can share a PR if that's easier. 

Also, it would be nice to have an `unfollow_my_position` function as well which keeps the center on the current position.

Thanks!

**Comment by podusowski** [comment]
Hi, sorry for such a late response. I am having a lot on my head lately. Yeah, the zoom thing seems to be worth having. I think `MapMemory::zoom() -> f32` should be a nice api for now (`Zoom` struct needs some rethinking and I am not sure where it will end up in).

As for `unfollow`, doesn't `center_at` do what you need? It is basically an opposite to what `follow_my_position` does.

**Comment by tfoldi** [comment]
hey, no need to be sorry, it is an open source project, I am grateful that you even replied :) 

I sent a PR with zoom changes; it will help me to implement a Slider on the UI.

For the `center_at` function, I need to provide the central Position, which I won't know unless it's saved in my application's state. Since the Map already knows its position, we could have a function that just unfollows, without adding any extra argument.

**Comment by podusowski** [comment]
Well, it does not. It is stored in certain `center_mode` variants, but gets lost when `follow_my_position` is called. Unless you want to center at current location, but then it is just `my_position` which you pass to `Map::new`.

**Comment by tfoldi** [comment]
gotcha, thank you
