### ISSUE TITLE
Use low-resolution tiles when zooming in and the high res tiles are not yet available

### ISSUE THREAD

**Issue by abey79** [podusowski/walkers#198]
Best effort background filling with lower-resolution tiles while hi-res tiles are being downloaded would greatly increase the user experience.

**Comment by podusowski** [comment]
There is https://github.com/podusowski/walkers/pull/201, but I'd like to keep it opened, as it only tries one-level down. It's an improvement, but it can be better.

**Comment by abey79** [comment]
Just tested 0.26. That one level already makes a great deal of difference! So much less background flashing!
