### ISSUE TITLE
Obsolete pending tile requests should be dropped

### ISSUE THREAD

**Issue by dwuertz** [podusowski/walkers#218]
Currently, if a requested tile has been queued for download via `HttpTiles::request_tile()`, it will eventually be processed no matter whether the tile is still being used or not by the time it becomes available. Worse, these obsolete requests will be processed before those most recently requested. Such situations occur when the user performs rapid zooming or viewport motions. This leads to unnecessary long stalls of map view updates as well as excessive requests to the tile service and should therefore be avoided.

**Comment by dwuertz** [comment]
I might have found a way to improve things with minimal effort. The number of pending tile requests is currently limited to 20:
https://github.com/podusowski/walkers/blob/2e88a3afd90294115757cf16937afc3940e7e107/walkers/src/tiles.rs#L106-L107
OTOH, at most one downloaded tile per frame is fetched from the queue:
https://github.com/podusowski/walkers/blob/2e88a3afd90294115757cf16937afc3940e7e107/walkers/src/tiles.rs#L138-L139
Since the second part limits the overall throughput to one tile per frame, we could also limited the request queue (channel) to 1 and hence avoid queuing up to 20 possibly outdated requests. Am I missing something here?

On the long term, a proper re-design could still be beneficial, in order to lift the current overall throttling (which could make a real-world difference in particular if tiles are fetched from the disk cache).

**Comment by podusowski** [comment]
There might be some interaction with how redraws are requested. So for example: redraw is requested because the app starts. Single tile request is put on the "queue", others are not. The first chance they get is after the next redraw, which will be happen only after a window event is fired, or when the first tile is downloaded.

I think.
