### ISSUE TITLE
Draw lines between coordinates

### ISSUE THREAD

**Issue by KookaburraShell** [podusowski/walkers#22]
Is there a way to draw a line, with whatever color, between two coordinates?

**Comment by podusowski** [comment]
Yes, although it's a bit tedious at the moment. There is a reference code for drawing stuff at some location:

https://github.com/podusowski/walkers/blob/main/examples/osm.rs#L71

rest is just using egui's `Painter` methods:

https://docs.rs/egui/latest/egui/struct.Painter.html#paint-different-primitives
