### ISSUE TITLE
Compilation error with Trunk

### ISSUE THREAD

**Issue by logankonopatzke** [podusowski/walkers#35]
Using version 0.7.0 compiling with cargo works fine. However, when attempting to build as WASM with trunk, I'm getting errors with visibility in Tokio. 

`
error[E0603]: module 'runtime' is private
   --> /Users/logankonopatzke/.cargo/registry/src/index.crates.io-6f17d22bba15001f/walkers-0.7.0/src/tokio.rs:16:34
    |
16  |             let runtime = tokio::runtime::Builder::new_current_thread()
    |                                  ^^^^^^^ private module
    |
note: the module 'runtime' is defined here
   --> /Users/logankonopatzke/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/lib.rs:540:5
    |
540 |     pub(crate) mod runtime;
`

This occurs when doing `trunk serve` or `trunk build` on MacOS.

**Comment by podusowski** [comment]
WASM is not supported at the moment, see https://github.com/podusowski/walkers/issues/34

**Comment by logankonopatzke** [comment]
Gotcha, thank you. I'll go ahead and close this.
