### ISSUE TITLE
Draw lines and markers to locations

### ISSUE THREAD

**Issue by AZProductions** [podusowski/walkers#4]
It would be cool to see a way to add markers and lines to the map. I don't know if it is possible without using other 3rd party map services like https://www.geoapify.com/static-maps-api or using vector maps.

Thanks!

**Comment by podusowski** [comment]
It's possible, although a little bit tedious. I've upgraded the example to demonstrate this.

**Comment by AZProductions** [comment]
To draw lines between 2 points epaint::PathShape could be used.
