### ISSUE TITLE
Wrong coordinates system?

### ISSUE THREAD

**Issue by ShadowMitia** [podusowski/walkers#62]
Hello!

I'm confused about the positions, I'm trying to center the map at spawn at a different location, I'm taking gps coordinates from google maps and openstreetmaps but each time it puts me in the wrong place.

These are the coordinates for the eiffel tower in france 48.85830,2.29451, it puts me in the ocean near the coast of somalia.

The positions in the demo also don't map to their locations in google maps  or openstreetmap.

Do I need to do something special to get gps coordinates onto the map?

**Comment by podusowski** [comment]
It's probably because walkers' Position takes lon lat, while lot of other things use lat lon.

I need to rethink this API.

**Comment by ShadowMitia** [comment]
Oh I see! It really got me!
I would suggest at least documenting it somewhere, I think it would be enough.
