### ISSUE TITLE
Panning viewport not smooth / imprecise location display at high zoom level

### ISSUE THREAD

**Issue by dwuertz** [podusowski/walkers#63]
At the highest zoom level, panning the map viewport via mouse drag is not smooth. Also, location markers may be off by several meters.

The reason is that currently, Mercator projections are computed using only single-precision floats (32-bit) , which is not enough to get results accurate to the pixel.

I have a prototype fix working based on the `glam` crate, that changes some internal types, such as `mercator::Pixels`, to `glam::f64::DVec2`.

If you are interested, I would be willing to prepare a PR.

**Comment by podusowski** [comment]
I'd love to see it! Maybe https://github.com/podusowski/walkers/pull/53 was a wrong direction. :)
