### ISSUE TITLE
Support disk cache for tile bitmaps

### ISSUE THREAD

**Issue by dwuertz** [podusowski/walkers#64]
Not only would persisting downloaded tile bitmaps on disk speed up map loading, I also believe it is implicitly mandated by the terms of use of some map providers such as OSM.

I have a straight-forward, basic prototype working here based on the `http-cache-reqwest` crate. Some open questions:
Should this behind a feature flag?
Should this be activated per provider (as some providers disallow caching) ?

**Comment by podusowski** [comment]
Yes, you're right, OSM requires caching.

> Should this behind a feature flag?

I believe so. I can imagine use-cases where read-write disk access isn't even possible. Also, I don't know how will it work on Android and WASM. Later seems to be using browser cache, so there are couple of interesting interactions before this becomes solid and stable.

> Should this be activated per provider (as some providers disallow caching) ?

I'd leave it for the future. Unless it's something which blocks your app in some way.
