### ISSUE TITLE
Possible for Jupyter Notebooks?

### ISSUE THREAD

**Issue by paulterinho** [podusowski/walkers#71]
Hi all, 

Just curious if this would be able to be used in a Jupyter Notebook context?

Paul

**Comment by podusowski** [comment]
I have zero experience with Rust in Jupyter I'm afraid. It basically boils down to whether [egui](https://github.com/emilk/egui) works there or not, though I haven't heard about such use case.

**Comment by paulterinho** [comment]
Probably not then, I'm not finding any online examples. Thanks for the feeback!
