### ISSUE TITLE
local-generated tiles

### ISSUE THREAD

**Issue by noktoborus** [podusowski/walkers#94]
I want to display locally-generated tiles using memory instead of HTTP transport.

How can this be done in the right way?

It seemed to me that it was right to convert `Tiles` to trait and make `Texture` public.

**Comment by podusowski** [comment]
Yes, I believe that would be the most straightforward solution.

**Comment by podusowski** [comment]
Assuming that internal http server is not suitable for you, because extending the API do have a cost.

**Comment by noktoborus** [comment]
Please, review this PR: https://github.com/podusowski/walkers/pull/97


here is my implementation and example with statuses:
https://github.com/noktoborus/osm-renderer/blob/e5be0b26385d3df7ed13a47bbcabdff9feae1c8e/src/terminal/local_osm_tiles.rs#L241
![image](https://github.com/podusowski/walkers/assets/324098/ff427055-88a3-4605-a268-935a9570c0dc)

**Comment by podusowski** [comment]
Will do, as soon as I get back from the holiday. :)

**Comment by noktoborus** [comment]
> Will do, as soon as I get back from the holiday. :)

Have a good rest! :)
